# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gender Neutral Austin
email: novacourtois@gmail.com
description: "We deserve to pee in peace."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://genderneutralaustin.com/" # the base hostname & protocol for your site
twitter_username: novacourtois
github_username:  novacourtois

# Build settings
markdown: kramdown


baseurl: ""
url: "http://disregardingstandards.com/genderneutralaustin/"
google_analytics:

include: ['_pages']
permalink: /:title/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: css
  style: :compressed